const List<Map<String, String>> countriesData = [
  {
    'nom': 'France',
    'capitale': 'Paris',
    'population': '67 millions d\'habitants',
    'superficie': '643 801 km²',
    'langues': 'Français',
    'flag': 'assets/images/france.png',
  },
  {
    'nom': 'Tunisie',
    'capitale': 'Tunis',
    'population': '12.4 millions d\'habitants',
    'superficie': '163 610 km²',
    'langues': 'Arabe',
    'flag': 'assets/images/Tunisia_Big.jpg',
  },
  {
    'nom': 'Brésil',
    'capitale': 'Brasília',
    'population': '215 millions d\'habitants',
    'superficie': '8 515 767 km²',
    'langues': 'Portugais',
    'flag': 'assets/images/bresil.png',
  },
  {
    'nom': 'Italie',
    'capitale': 'Rome',
    'population': '59 millions d\'habitants',
    'superficie': '301 340 km²',
    'langues': 'Italien',
    'flag': 'assets/images/italie.png',
  },
  {
    'nom': 'Canada',
    'capitale': 'Ottawa',
    'population': '39 millions d\'habitants',
    'superficie': '9 984 670 km²',
    'langues': 'Anglais, Français',
    'flag': 'assets/images/canada.png',
  },
  {
    'nom': 'Australie',
    'capitale': 'Canberra',
    'population': '26 millions d\'habitants',
    'superficie': '7 692 024 km²',
    'langues': 'Anglais',
    'flag': 'assets/images/australie.png',
  },
  {
    'nom': 'Allemagne',
    'capitale': 'Berlin',
    'population': '84 millions d\'habitants',
    'superficie': '357 022 km²',
    'langues': 'Allemand',
    'flag': 'assets/images/allemagne.png',
  },
  {
    'nom': 'Espagne',
    'capitale': 'Madrid',
    'population': '47 millions d\'habitants',
    'superficie': '505 990 km²',
    'langues': 'Espagnol',
    'flag': 'assets/images/espagne.png',
  },
  {
    'nom': 'Afrique du Sud',
    'capitale': 'Pretoria',
    'population': '60 millions d\'habitants',
    'superficie': '1 219 090 km²',
    'langues': 'Afrikaans, Anglais',
    'flag': 'assets/images/afrique_du_sud.png',
  },
];
